_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-arm64
batch_size:
    value: 128
dropout:
    value: 0.1
epochs:
    value: 1
lr:
    value: 0.001
slice_size:
    value: 10000
valid_pct:
    value: 0.2
